dist: trusty
install:
  - npm config set package-lock false
  - npm install
  - npm install -g cypress-cli
  - npm run build
addons:
  chrome: stable
language: node_js
cache:
  directories:
    - "node_modules"
jobs:
  inlcude:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
