dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
    - "node_modules"
install:
  - npm i
  - cypress install
jobs:
  inlcude:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
